plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/brian/python-projects/boston-finder-repo/docs"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]