"""
Persona registry — all persona config lives here.

To archive someone: set active=False. Their full profile stays intact.
To bring them back: set active=True. Everything reconnects.
"""

from boston_finder.location import PROXIMITY

# ── Registry ────────────────────────────────────────────────────────

PERSONAS: dict[str, dict] = {
    "brian": {
        "active": True,
        "title": "Boston Events",
        "nav_label": "Brian",
        "accent": "#f0a500",
        "url_path": "/",              # index.html
        "deploy_file": "index.html",
        "proximity": None,            # uses default PROXIMITY table
    },
    "dates": {
        "active": True,
        "title": "Date Ideas",
        "nav_label": "Dates",
        "accent": "#c084fc",
        "url_path": "/dates",
        "deploy_file": "dates.html",
        "proximity": {
            **PROXIMITY,
            # dates persona uses Back Bay as home base
            "Back Bay":        10,
            "South End":        9,
            "Beacon Hill":      9,
            "Newbury Street":  10,
            "Fenway":           8,
            "Kenmore":          8,
            "Downtown":         8,
            "Seaport":          6,
            "Cambridge":        5,
            "Brookline":        6,
            "Chestnut Hill":    3,
        },
    },
    "kirk": {
        "active": True,
        "title": "Kirk's Boston",
        "nav_label": "Kirk",
        "accent": "#38bdf8",
        "url_path": "/kirk",
        "deploy_file": "kirk.html",
        "proximity": None,            # Kirk has a car, no proximity filtering
        "static": True,               # client-side rendered, not generated by Python
    },
    "chloe": {
        "active": False,
        "title": "Chloe's Boston",
        "nav_label": "Chloe",
        "accent": "#c084fc",
        "url_path": "/chloe",
        "deploy_file": "chloe.html",
        "proximity": {
            **PROXIMITY,
            # Chloe was in Back Bay
            "Back Bay":        10,
            "South End":        9,
            "Beacon Hill":      9,
            "Newbury Street":  10,
            "Fenway":           8,
            "Kenmore":          8,
            "Downtown":         8,
            "Seaport":          6,
            "Cambridge":        5,
            "Brookline":        6,
            "Chestnut Hill":    3,
        },
        "prompt": (
            "You are filtering Boston events for Chloe, who wants upscale, "
            "interesting things to do in Boston.\n"
            "She loves:\n"
            "- Art: gallery openings, museum events, art shows, artist talks, "
            "art fairs, photography exhibits, sculpture\n"
            "- Food & drink: wine tastings, wine dinners, chef's table experiences, "
            "cocktail classes, food festivals, upscale restaurant events, mixology\n"
            "- Fancy experiences: galas, benefit dinners, charity auctions, cultural "
            "receptions, film premieres, theater openings\n"
            "- Design, fashion, and aesthetics — runway shows, design events, "
            "interior/architecture tours\n"
            "- Wellness and beauty events that are upscale (spa launches, product "
            "launches, brand events)\n"
            "- Anything cultured, beautiful, or scene-y\n\n"
            "Lower priority for her:\n"
            "- Pure civic/government/policy events (unless they're glamorous)\n"
            "- Sports\n"
            "- Basic networking mixers with no food/drink/art angle\n\n"
            "Score 0-10. Only return events with score >= 5."
        ),
    },
}

SITE_BASE = "https://highendeventfinder.netlify.app"


# ── Public API ──────────────────────────────────────────────────────

def get_persona(name: str) -> dict:
    """Return persona config. Raises RuntimeError if archived or unknown."""
    p = PERSONAS.get(name)
    if p is None:
        raise RuntimeError(f"unknown persona: {name}")
    if not p["active"]:
        raise RuntimeError(f"persona '{name}' is archived — flip active=True in personas.py to restore")
    return p


def get_proximity(name: str) -> dict | None:
    """Return proximity table for a persona, or None for default."""
    p = PERSONAS.get(name)
    if p is None:
        return None
    return p.get("proximity")


def active_personas() -> list[dict]:
    """Return all active personas in display order."""
    return [
        {"name": k, **v}
        for k, v in PERSONAS.items()
        if v["active"]
    ]


def nav_html(current: str) -> str:
    """Build nav bar markup for the current persona."""
    links = []
    for p in active_personas():
        url = f"{SITE_BASE}{p['url_path']}"
        cls = "nav-active" if p["name"] == current else "nav-link"
        links.append(f'<a href="{url}" class="{cls}">{p["nav_label"]}</a>')
    return "\n    ".join(links)
